{{- $cluster := $.Values.cluster -}}
{{- range $name, $app := .Values.helmApplications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-gitops-{{ $name }}-stage1
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: {{ $cluster.repo }}
    path: {{ $cluster.repoPathPrefix }}/stage2
    helm:
      releaseName: {{ $name }}-{{ $cluster.name }}
      valueFiles:
      - ../../clusters/{{ $cluster.name }}/cluster.yaml
      fileParameters:
      - name: stage2.helmApplications.{{ $name }}.content
        path: {{ $app.addonFile }}
---
{{- end }}
